"""PurchaseOrder: remove unnecessaru fields

Revision ID: 02b566030ea9
Revises: 4ddcebb9f3be
Create Date: 2025-08-06 13:09:09.847830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b566030ea9'
down_revision: Union[str, Sequence[str], None] = '4ddcebb9f3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('purchase_orders.py_product_id_fkey'), 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('purchase_orders.py_product_id_fkey'), 'purchase_orders', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
