"""inventory model : added sku field

Revision ID: 09dca07f2990
Revises: 2042012c6334
Create Date: 2025-08-08 03:15:26.657651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09dca07f2990'
down_revision: Union[str, Sequence[str], None] = '2042012c6334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('sku', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'sku')
    # ### end Alembic commands ###
