"""POModel: added warehouse_id 

Revision ID: 130eeccede7b
Revises: 4cf54526512f
Create Date: 2025-08-07 10:44:45.347686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130eeccede7b'
down_revision: Union[str, Sequence[str], None] = '4cf54526512f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('warehouse_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'purchase_orders', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'warehouse_id')
    # ### end Alembic commands ###
