"""InventoryItem : remove po_item field and added warehouse_id field

Revision ID: 2042012c6334
Revises: b9748798b2ce
Create Date: 2025-08-07 19:51:59.231423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2042012c6334'
down_revision: Union[str, Sequence[str], None] = 'b9748798b2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('warehouse_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('inventory_items_po_item_id_fkey'), 'inventory_items', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_items', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_column('inventory_items', 'po_item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('po_item_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_items_po_item_id_fkey'), 'inventory_items', 'purchase_order_items', ['po_item_id'], ['id'])
    op.drop_column('inventory_items', 'warehouse_id')
    # ### end Alembic commands ###
