"""PRODUCT MODEL: make qty field default with value 0

Revision ID: 290ae1149936
Revises: 311e5f96546d
Create Date: 2025-08-05 18:16:22.856788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '290ae1149936'
down_revision: Union[str, Sequence[str], None] = '311e5f96546d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('model', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'model')
    # ### end Alembic commands ###
