"""Added poitems model and establish relationship between po and poitems

Revision ID: 2ac6f8f8f0d2
Revises: 02b566030ea9
Create Date: 2025-08-06 13:18:58.555617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac6f8f8f0d2'
down_revision: Union[str, Sequence[str], None] = '02b566030ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('total_po_cost', sa.Integer(), nullable=False))
    op.drop_column('purchase_orders', 'total_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('total_cost', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('purchase_orders', 'total_po_cost')
    # ### end Alembic commands ###
