"""PRODUCT MODEL: remove brand_code field

Revision ID: 311e5f96546d
Revises: 58f990d48d50
Create Date: 2025-08-05 18:06:41.022573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311e5f96546d'
down_revision: Union[str, Sequence[str], None] = '58f990d48d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'brand_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
