"""Added available_unit field into bin model and available_bins in warehosue model 

Revision ID: 319ad32a7fe2
Revises: fabb6aedbde7
Create Date: 2025-08-07 18:31:05.765828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319ad32a7fe2'
down_revision: Union[str, Sequence[str], None] = 'fabb6aedbde7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bins', sa.Column('current_stock_units', sa.Integer(), nullable=False))
    op.add_column('bins', sa.Column('available_units', sa.Integer(), nullable=False))
    op.drop_column('bins', 'available_unit')
    op.drop_column('bins', 'current_stock_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bins', sa.Column('current_stock_unit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bins', sa.Column('available_unit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('bins', 'available_units')
    op.drop_column('bins', 'current_stock_units')
    # ### end Alembic commands ###
