"""warehouse Mdoel: remove qty field

Revision ID: 32b27ba0f787
Revises: d5b5626cd656
Create Date: 2025-08-06 11:20:55.142995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b27ba0f787'
down_revision: Union[str, Sequence[str], None] = 'd5b5626cd656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
