"""POItem  Model :rename toatl_cost to total_cost

Revision ID: 47b46428eafe
Revises: 943c2712149f
Create Date: 2025-08-06 17:10:04.898887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b46428eafe'
down_revision: Union[str, Sequence[str], None] = '943c2712149f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_items', sa.Column('total_cost', sa.Integer(), nullable=False))
    op.drop_column('purchase_order_items', 'toatl_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_items', sa.Column('toatl_cost', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('purchase_order_items', 'total_cost')
    # ### end Alembic commands ###
