"""Product Model: added product id field

Revision ID: 4cf54526512f
Revises: 47b46428eafe
Create Date: 2025-08-07 06:12:04.510344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf54526512f'
down_revision: Union[str, Sequence[str], None] = '47b46428eafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_items', sa.Column('product_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'purchase_order_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_order_items', type_='foreignkey')
    op.drop_column('purchase_order_items', 'product_id')
    # ### end Alembic commands ###
