"""PurchaseOrder: remove unnecessaru fields

Revision ID: 4ddcebb9f3be
Revises: 54005a885bcd
Create Date: 2025-08-06 13:02:22.869471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddcebb9f3be'
down_revision: Union[str, Sequence[str], None] = '54005a885bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('expected_date', sa.DateTime(), nullable=False))
    op.drop_column('purchase_orders', 'unit_cost')
    op.drop_column('purchase_orders', 'qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('purchase_orders', sa.Column('unit_cost', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('purchase_orders', 'expected_date')
    # ### end Alembic commands ###
