"""warehouse Mdoel: rename field capacity -> capacity_in_sqft

Revision ID: 54005a885bcd
Revises: 32b27ba0f787
Create Date: 2025-08-06 11:24:00.218107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54005a885bcd'
down_revision: Union[str, Sequence[str], None] = '32b27ba0f787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('capacity_in_sqft', sa.Integer(), nullable=False))
    op.drop_column('warehouses', 'capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('warehouses', 'capacity_in_sqft')
    # ### end Alembic commands ###
