"""POItem  Model :rename toatl_cost to total_cost

Revision ID: 943c2712149f
Revises: e3958299564d
Create Date: 2025-08-06 17:09:24.617180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943c2712149f'
down_revision: Union[str, Sequence[str], None] = 'e3958299564d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
