"""added max_units and current_stock_qty into Bin model and max_bins,current_bins add into warehousemodel

Revision ID: 9918dd5e4d8b
Revises: 130eeccede7b
Create Date: 2025-08-07 11:36:38.697340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9918dd5e4d8b'
down_revision: Union[str, Sequence[str], None] = '130eeccede7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bins', sa.Column('max_units', sa.Integer(), nullable=False))
    op.add_column('bins', sa.Column('current_stock_qty', sa.Integer(), nullable=False))
    op.add_column('warehouses', sa.Column('max_bins', sa.Integer(), nullable=False))
    op.add_column('warehouses', sa.Column('current_bins', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'current_bins')
    op.drop_column('warehouses', 'max_bins')
    op.drop_column('bins', 'current_stock_qty')
    op.drop_column('bins', 'max_units')
    # ### end Alembic commands ###
