"""Remove category column from product model

Revision ID: 9989c0a39768
Revises: c3b57d7e6b54
Create Date: 2025-08-04 19:37:01.665544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9989c0a39768'
down_revision: Union[str, Sequence[str], None] = 'c3b57d7e6b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
