"""Product Model: make sku not unique

Revision ID: b2398275db79
Revises: cb8ed059be93
Create Date: 2025-08-06 10:44:35.817728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2398275db79'
down_revision: Union[str, Sequence[str], None] = 'cb8ed059be93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_sku_key'), 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('products_sku_key'), 'products', ['sku'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
