"""PURCHASEORDER MODEL: remove lead_time_days field

Revision ID: b4b6f9fcaf3f
Revises: 94943c209b3a
Create Date: 2025-08-05 18:28:55.771899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b6f9fcaf3f'
down_revision: Union[str, Sequence[str], None] = '94943c209b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders.py', 'lead_time_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders.py', sa.Column('lead_time_days', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
