"""receivePOItemModel : added po_id field

Revision ID: b9748798b2ce
Revises: 319ad32a7fe2
Create Date: 2025-08-07 19:01:27.627239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9748798b2ce'
down_revision: Union[str, Sequence[str], None] = '319ad32a7fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('received_po_items', sa.Column('po_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'received_po_items', 'purchase_orders', ['po_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'received_po_items', type_='foreignkey')
    op.drop_column('received_po_items', 'po_id')
    # ### end Alembic commands ###
