"""ProductModel: added threshold_qty field with default 0

Revision ID: b9913058eb8f
Revises: d43a27b867d3
Create Date: 2025-08-08 12:19:55.783647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9913058eb8f'
down_revision: Union[str, Sequence[str], None] = 'd43a27b867d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('threshold_qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'threshold_qty')
    # ### end Alembic commands ###
