"""Bin model: set current_stock_qty with default 0

Revision ID: c78c06c497cc
Revises: 9918dd5e4d8b
Create Date: 2025-08-07 12:18:35.315439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78c06c497cc'
down_revision: Union[str, Sequence[str], None] = '9918dd5e4d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
