"""warehouse Mdoel: add manager_id field

Revision ID: d5b5626cd656
Revises: b2398275db79
Create Date: 2025-08-06 11:06:08.032183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b5626cd656'
down_revision: Union[str, Sequence[str], None] = 'b2398275db79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('capacity', sa.Integer(), nullable=False))
    op.add_column('warehouses', sa.Column('warehouse_manager_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'warehouses', 'users', ['warehouse_manager_id'], ['id'])
    op.drop_column('warehouses', 'capicity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('capicity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'warehouse_manager_id')
    op.drop_column('warehouses', 'capacity')
    # ### end Alembic commands ###
