"""product Model :remove fields qty and cost

Revision ID: e3958299564d
Revises: c2ea60df4a44
Create Date: 2025-08-06 16:46:10.633826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3958299564d'
down_revision: Union[str, Sequence[str], None] = 'c2ea60df4a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'cost')
    op.drop_column('products', 'qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
