"""Added available_unit field into bin model and available_bins in warehosue model 

Revision ID: fabb6aedbde7
Revises: 0c19b0aae306
Create Date: 2025-08-07 18:25:33.179939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fabb6aedbde7'
down_revision: Union[str, Sequence[str], None] = '0c19b0aae306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bins', sa.Column('current_stock_unit', sa.Integer(), nullable=False))
    op.add_column('bins', sa.Column('available_unit', sa.Integer(), nullable=False))
    op.drop_column('bins', 'current_stock_qty')
    op.add_column('warehouses', sa.Column('available_bins', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'available_bins')
    op.add_column('bins', sa.Column('current_stock_qty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('bins', 'available_unit')
    op.drop_column('bins', 'current_stock_unit')
    # ### end Alembic commands ###
