"""ReceivedPOItem : added from_warehouse_id and to_warehouse_id field

Revision ID: ff7f780acc8b
Revises: b9913058eb8f
Create Date: 2025-08-08 14:43:44.972820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff7f780acc8b'
down_revision: Union[str, Sequence[str], None] = 'b9913058eb8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('received_po__items_or_from_warehouse',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=True),
    sa.Column('from_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('to_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('received_po_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('received_po_items',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('po_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('received_po_items_po_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('received_po_items_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('received_po_items_pkey'))
    )
    op.drop_table('received_po__items_or_from_warehouse')
    # ### end Alembic commands ###
